# static_map - True if using existing map

global_costmap:
  global_frame: odom
  robot_base_frame: chassis
  update_frequency: 1.0
  publish_frequency: 1.0
  resolution: 1
  static_map: false
  always_send_full_costmap: true
  static_layer: {enabled: true, lethal_cost_threshold: 100, track_unknown_space: true, unknown_cost_value: -1}
  rolling_window: true
  width: 200.0
  height: 200.0
