local_costmap:
  global_frame: odom
  robot_base_frame: chassis
  update_frequency: 2.0
  publish_frequency: 1.0
  static_map: false
  always_send_full_costmap: true
  rolling_window: true
  width: 10.0
  height: 10.0
  resolution: 0.05
